### ISSUE TITLE
Error "The credentials provided cannot be used for the SQL source"

### ISSUE THREAD

**Issue by ButescuRares** [NandanHegde15/Azure-DataFactory-Generic-Pipelines#2]
Hello,

Implemented the same logic presented in the repo in my pipeline as well but encountered this generic error. 
I am trying to refresh a model from within Azure Analysis Service. 
The complete error message is:
" The credentials provided cannot be used for the SQL source. (Source at example.database.windows.net;exampledb.). The exception was raised by the IDbCommand interface. "

**Comment by NandanHegde15** [comment]
Hey @ButescuRares ,
Can you please confirm whether the source for your AAS is Azure SQL database and what credentials are you using to access it?
Are those SQL creds
